version: '3.8'

services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  # Usando a variável de ambiente para senha
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Usando a variável de ambiente para senha do root
      MYSQL_ROOT_HOST: '%'  # Permitindo acesso remoto ao usuário root (cuidado em produção)
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped  # Reinicia automaticamente se o container falhar

volumes:
  mysql_data:
    driver: local  # Garante que os dados sejam persistidos em um volume local